# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'design2.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QMainWindow, QPushButton,
    QScrollArea, QScrollBar, QSizePolicy, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(684, 842)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(50, 20, 59, 17))
        font = QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(50, 60, 581, 71))
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 571, 61))
        self.verticalScrollBar_5 = QScrollBar(self.scrollAreaWidgetContents)
        self.verticalScrollBar_5.setObjectName(u"verticalScrollBar_5")
        self.verticalScrollBar_5.setGeometry(QRect(560, 0, 16, 61))
        self.verticalScrollBar_5.setOrientation(Qt.Vertical)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(50, 150, 59, 17))
        self.label_2.setFont(font)
        self.scrollArea_2 = QScrollArea(self.centralwidget)
        self.scrollArea_2.setObjectName(u"scrollArea_2")
        self.scrollArea_2.setGeometry(QRect(50, 190, 581, 71))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollAreaWidgetContents_3 = QWidget()
        self.scrollAreaWidgetContents_3.setObjectName(u"scrollAreaWidgetContents_3")
        self.scrollAreaWidgetContents_3.setGeometry(QRect(0, 0, 571, 61))
        self.verticalScrollBar_4 = QScrollBar(self.scrollAreaWidgetContents_3)
        self.verticalScrollBar_4.setObjectName(u"verticalScrollBar_4")
        self.verticalScrollBar_4.setGeometry(QRect(560, 0, 16, 61))
        self.verticalScrollBar_4.setOrientation(Qt.Vertical)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(48, 280, 59, 17))
        self.label_3.setFont(font)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(48, 410, 59, 17))
        self.label_4.setFont(font)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(50, 540, 59, 17))
        self.label_5.setFont(font)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(50, 670, 151, 17))
        self.label_6.setFont(font)
        self.scrollArea_3 = QScrollArea(self.centralwidget)
        self.scrollArea_3.setObjectName(u"scrollArea_3")
        self.scrollArea_3.setGeometry(QRect(50, 320, 581, 71))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 571, 61))
        self.verticalScrollBar_3 = QScrollBar(self.scrollAreaWidgetContents_2)
        self.verticalScrollBar_3.setObjectName(u"verticalScrollBar_3")
        self.verticalScrollBar_3.setGeometry(QRect(560, 0, 16, 61))
        self.verticalScrollBar_3.setOrientation(Qt.Vertical)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_2)
        self.scrollArea_4 = QScrollArea(self.centralwidget)
        self.scrollArea_4.setObjectName(u"scrollArea_4")
        self.scrollArea_4.setGeometry(QRect(50, 450, 581, 71))
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollAreaWidgetContents_4 = QWidget()
        self.scrollAreaWidgetContents_4.setObjectName(u"scrollAreaWidgetContents_4")
        self.scrollAreaWidgetContents_4.setGeometry(QRect(0, 0, 571, 61))
        self.verticalScrollBar_2 = QScrollBar(self.scrollAreaWidgetContents_4)
        self.verticalScrollBar_2.setObjectName(u"verticalScrollBar_2")
        self.verticalScrollBar_2.setGeometry(QRect(560, 0, 16, 61))
        self.verticalScrollBar_2.setOrientation(Qt.Vertical)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.scrollArea_5 = QScrollArea(self.centralwidget)
        self.scrollArea_5.setObjectName(u"scrollArea_5")
        self.scrollArea_5.setGeometry(QRect(50, 580, 581, 71))
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollAreaWidgetContents_5 = QWidget()
        self.scrollAreaWidgetContents_5.setObjectName(u"scrollAreaWidgetContents_5")
        self.scrollAreaWidgetContents_5.setGeometry(QRect(0, 0, 571, 61))
        self.verticalScrollBar = QScrollBar(self.scrollAreaWidgetContents_5)
        self.verticalScrollBar.setObjectName(u"verticalScrollBar")
        self.verticalScrollBar.setGeometry(QRect(560, 0, 16, 61))
        self.verticalScrollBar.setOrientation(Qt.Vertical)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.scrollArea_6 = QScrollArea(self.centralwidget)
        self.scrollArea_6.setObjectName(u"scrollArea_6")
        self.scrollArea_6.setGeometry(QRect(50, 710, 581, 71))
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollAreaWidgetContents_6 = QWidget()
        self.scrollAreaWidgetContents_6.setObjectName(u"scrollAreaWidgetContents_6")
        self.scrollAreaWidgetContents_6.setGeometry(QRect(0, 0, 571, 61))
        self.verticalScrollBar_6 = QScrollBar(self.scrollAreaWidgetContents_6)
        self.verticalScrollBar_6.setObjectName(u"verticalScrollBar_6")
        self.verticalScrollBar_6.setGeometry(QRect(560, 0, 16, 61))
        self.verticalScrollBar_6.setOrientation(Qt.Vertical)
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_6)
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(540, 790, 93, 39))
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(500, 10, 131, 39))
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(500, 140, 131, 41))
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(500, 270, 131, 39))
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(500, 400, 131, 39))
        self.pushButton_6 = QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(500, 530, 131, 39))
        self.pushButton_7 = QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(500, 660, 131, 39))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"grokJLPT", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"N5", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"N4", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"N3", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"N2", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"N1", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Outside JLPT", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Close", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Copy to clipboard", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Copy to clipboard", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Copy to clipboard", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"Copy to clipboard", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"Copy to clipboard", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"Copy to clipboard", None))
    # retranslateUi

